### ISSUE TITLE
Install the ruby gem for rouge syntax highlighter

### ISSUE THREAD

**Issue by rolfedh** [shipwright-io/website#87] opened 2022-09-05 19:10 UTC
As a contributor creating content in asciidoc files, I would like the website to have the the asciidoctor-rouge extension that the [External Helper Asciidoctor](https://gohugo.io/content-management/formats/#external-helper-asciidoctor) mentions.

 This is a follow-up task from Adam's suggestion in https://github.com/shipwright-io/website/issues/85 :
> Seems simple enough to add Rouge - we would just need to add the appropriate Ruby gem:
> 
> https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/rouge/#install-rouge

**Comment by rolfedh** [comment] 2022-09-05 19:16
/assign @SaschaSchwarze0 
Who might be the best person to do this task?

**Comment by SaschaSchwarze0** [comment] 2022-09-06 06:47
Duplicate of https://github.com/shipwright-io/website/issues/85. And certainly not me who has no knowledge of Ruby. Based on [ this comment](https://github.com/shipwright-io/community/issues/100#issuecomment-1215020481), @adambkaplan wanted to help you. Please work with him.

**Closed by SaschaSchwarze0** 2022-09-06 06:47 UTC
